// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayeyyfhypqefyyybshjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZXl5Zmh5cHFlZnl5eWJzaGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDAwMDAsImV4cCI6MjA2NjcxNjAwMH0.0Y7uZgKcc3xV6SKGrEhb5GSI5n4mEhTXqtaKeigE-_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);